---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        exclude: test_data/.*\.py$
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: importanize
      name: importanize
      entry: python -m importanize
      language: system
      language_version: python3
      types: [python]
      args: [-v]

  - repo: https://github.com/ambv/black
    sha: 'master'
    hooks:
      - id: black
        args: [--line-length=80, --safe]
        language_version: python3
        exclude: test_data/.*\.py$
